import com.sparkine.muvizedge.adaptive.CaptureStartPolicy;
public final class CaptureStartPolicyTest {
    static int checks;
    static void check(boolean ok,String label){if(!ok)throw new AssertionError(label);checks++;}
    public static void main(String[] args){
        check(CaptureStartPolicy.supported(30,true,true,true),"Android 11 car experiment enabled");
        check(!CaptureStartPolicy.supported(30,false,true,true),"phone unchanged");
        check(!CaptureStartPolicy.supported(33,false,true,true),"Android 13 phone unchanged");
        check(!CaptureStartPolicy.supported(33,true,true,true),"other ROM versions unchanged");
        check(!CaptureStartPolicy.supported(29,true,true,true),"old Android unchanged");
        check(!CaptureStartPolicy.supported(34,true,true,true),"do not extend to newer FGS restrictions");
        check(!CaptureStartPolicy.supported(30,true,false,true),"compat off disables experiment");
        check(!CaptureStartPolicy.supported(30,true,true,false),"comparison toggle disables experiment");
        CaptureStartPolicy p=new CaptureStartPolicy(false);
        check(p.choose(20000,130,0,false,false,false,false,false,false)==130,"legacy immediately uses microphone type");
        check(!p.waiting(),"legacy never suppresses prior recovery");
        p=new CaptureStartPolicy(true);
        check(p.choose(20000,130,0,false,false,false,true,false,false)==2,"initial foreground notification is immediate media type");
        check(p.waiting(),"staging suspends destructive service recovery");
        check(p.choose(30000,130,2,false,true,false,true,true,false)==2,"playback before boot ready waits");
        check(p.choose(59999,130,2,false,true,false,true,true,false)==2,"missing boot signal waits below fallback");
        check(p.choose(60000,130,2,false,true,false,true,true,false)==130,"missing broadcast cannot block forever");
        check(!p.waiting(),"release enables existing failure recovery");
        check(p.choose(60500,130,130,false,true,false,true,false,false)==130,"pause never downgrades active microphone type");
        check(p.choose(90000,130,130,false,true,true,false,false,false)==130,"sleep does not oscillate types");
        p=new CaptureStartPolicy(true);
        check(p.choose(20000,130,2,false,true,false,true,true,false)==2,"start settling");
        check(p.choose(21499,130,2,false,true,true,true,true,false)==2,"boot signal still respects stable playback");
        check(p.choose(21500,130,2,false,true,true,true,true,false)==130,"actual boot signal avoids unnecessary minute wait");
        p=new CaptureStartPolicy(true);
        check(p.choose(100000,130,2,false,true,false,true,true,false)==2,"late process starts still wait for settled playback");
        check(p.choose(101000,130,2,false,true,false,true,false,false)==2,"pause resets initial playback settling");
        check(p.choose(102000,130,2,false,true,false,true,true,false)==2,"resume begins new stable window");
        check(p.choose(103499,130,2,false,true,false,true,true,false)==2,"resume window not yet met");
        check(p.choose(103500,130,2,false,true,false,true,true,false)==130,"resume releases exactly once");
        check(p.choose(104000,130,2,false,true,false,true,false,false)==130,"pending type upgrade not canceled by transient pause");
        check(p.choose(104001,130,130,false,true,false,true,true,false)==130,"delivered upgrade stays active");
        p=new CaptureStartPolicy(true);
        check(p.choose(100000,130,2,false,true,true,false,true,false)==2,"locked or screen off cannot begin playback window");
        check(p.choose(110000,130,2,false,true,true,true,true,false)==2,"unlock starts fresh window");
        check(p.choose(111500,130,2,false,true,true,true,true,false)==130,"unlocked playback releases");
        p=new CaptureStartPolicy(true);
        check(p.choose(20000,130,0,true,false,false,false,false,false)==130,"real visible activity bypasses background staging");
        check(p.choose(20001,130,130,false,true,false,true,false,false)==130,"leaving UI retains microphone type");
        p=new CaptureStartPolicy(true);
        check(p.choose(20000,2,0,false,false,false,false,false,false)==2,"no permission or AOD-only needs media type only");
        check(!p.waiting(),"no capture demand does not count as waiting to capture");
        check(p.choose(100000,130,2,false,true,true,true,true,false)==2,"permission grant begins staged path");
        check(p.choose(101500,130,2,false,true,true,true,true,false)==130,"permission grant can later release");
        check(p.choose(102000,2,130,false,true,true,true,true,false)==2,"permission revocation is respected");
        p=new CaptureStartPolicy(true);
        check(p.choose(100000,130,2,false,true,true,true,true,true)==2,"real FFT including silence protects working media service");
        check(!p.waiting(),"healthy hold is not startup failure waiting");
        check("healthy_media_hold".equals(p.phase()),"healthy hold explicitly diagnosed");
        check(p.choose(150000,130,2,false,true,true,true,true,true)==2,"continuous FFT never triggers needless upgrade");
        check(p.choose(150001,130,2,false,true,true,true,true,false)==2,"lost capture starts stable recovery window");
        check(p.choose(151501,130,2,false,true,true,true,true,false)==130,"loss after initial success can still upgrade");
        check(p.choose(151502,130,2,false,true,true,true,true,true)==2,"FFT arriving before command delivery suppresses upgrade");
        check(p.choose(151503,130,130,false,true,true,true,false,false)==130,"already applied type is not downgraded");
        p=new CaptureStartPolicy(true);
        check(p.choose(100000,130,2,false,true,true,true,true,false)==2,"prepare readiness loss");
        check(p.choose(101000,130,2,false,false,true,true,true,false)==2,"service becoming unready resets settling");
        check(p.choose(102000,130,2,false,true,true,true,true,false)==2,"new ready window begins");
        check(p.choose(103500,130,2,false,true,true,true,true,false)==130,"ready window eventually releases");
        p=new CaptureStartPolicy(true);
        check(p.choose(100000,130,2,false,true,true,true,true,false)==2,"prepare clock rollback");
        check(p.choose(1000,130,2,false,true,true,true,true,false)==2,"clock rollback resets ages");
        check(p.choose(2499,130,2,false,true,true,true,true,false)==2,"rollback cannot release early");
        check(p.choose(2500,130,2,false,true,true,true,true,false)==130,"rollback cannot stall forever");
        p=new CaptureStartPolicy(true);
        check(p.choose(200000,130,2,false,true,true,true,true,false)==2,"new service has its own settling state");
        check(p.choose(201500,130,2,false,true,true,true,true,false)==130,"new service releases independently");
        System.out.println("PASS: "+checks+" staged capture startup checks");
    }
}
